### ISSUE TITLE
Pin to semver string

### ISSUE THREAD

**Issue by jmcarp** [concourse/bosh-io-release-resource#12]
It would be useful to pin to a semver range, like ^2.7.0 or ~2.7.0, so that users can keep current without risking breaking changes. For example, I'd like to use this to avoid upgrading concourse to a new major release before all the kinks get ironed out 😉.

**Comment by jtarchie** [comment]
@jmcarp, there are no plans to support this directly in the resource directly. We'd like to do concourse/concourse#1176, so all resources can have this feature.
