### ISSUE TITLE
Is there a way to get a specific version of release?

### ISSUE THREAD

**Issue by MinsuLim** [concourse/bosh-io-release-resource#13]
Hi friends,

I'm using concourse to get github release of pivotal-cf/cf-redis-release and deploy it to bosh.
But I don't know how to get a specific version of releases.

'version_family' worked correctly for me in type  'bosh-io-stemcell' to get a specific version.
But I couldn't find any key word for type 'bosh-io-release'.   (version, version_family didn't work)
I get always latest version '431.0.0' while I'm looking for a specific version like '429.0.0' 

Is there a way to get a specific version of release?
Thank you for helping me in advance.

**Comment by dinomiteX** [comment]
I have the same Issue. Would be great to get something like "version_family" :)

**Comment by vito** [comment]
This can be done for *any* resource using [`version` on the `get` step](https://concourse.ci/get-step.html#get-step-version).
