### ISSUE TITLE
add sha1 as a file for bosh-io-releases

### ISSUE THREAD

**Issue by haydonryan** [concourse/bosh-io-release-resource#6]
Creating automated updates of deployments require the pipeline to know the sha1 of the release. (for bosh)

It'd be great to have this put into a separate file for use in scripts.

**Comment by vito** [comment]
@cppforlife is there any way to get this info from the bosh.io API?

**Comment by cppforlife** [comment]
existing releases api returns sha1 with each release url.

**Comment by vito** [comment]
not seeing it here:

https://bosh.io/api/v1/releases/github.com/concourse/concourse

**Comment by cppforlife** [comment]
ah fair enough not enabled... will show
